# Generated by Django 4.2.9 on 2024-01-12 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_truck_admin', '0002_foodtruckinfo_cuisine_type_menu_foodtrucklocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_gluten_free',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_vegetarian',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.AlterField(
            model_name='foodtrucklocation',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_truck_admin.menu')),
            ],
        ),
    ]
